# -*- coding: utf-8 -*-
"""pre_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8zxMtedJKVwgnAjr5Sqfchx1Q6Oaypq
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Identify numerical columns from the data dictionary
numeric_cols_for_plot = data_dictionary_df[
    data_dictionary_df['Inferred/Converted Data Type'] == 'Numeric'
]['Column Name'].tolist()

print(f"Plotting histograms for {len(numeric_cols_for_plot)} numerical columns...")

# Set up the matplotlib figure and axes for subplots
num_plots = len(numeric_cols_for_plot)
if num_plots > 0:
    # Determine optimal grid size. Max 4 columns per row for readability.
    n_cols = 4
    n_rows = (num_plots + n_cols - 1) // n_cols # Calculate rows needed

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4))
    axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

    for i, col in enumerate(numeric_cols_for_plot):
        # Ensure the column is numeric before plotting
        # Use pd.to_numeric with errors='coerce' to handle non-numeric entries gracefully
        numeric_series = pd.to_numeric(df[col], errors='coerce').dropna()

        if not numeric_series.empty:
            sns.histplot(numeric_series, kde=True, ax=axes[i], bins=20)
            axes[i].set_title(f'Distribution of {col}', fontsize=12)
            axes[i].set_xlabel(col)
            axes[i].set_ylabel('Frequency')
        else:
            # Hide empty subplots if a column couldn't be plotted
            axes[i].axis('off')

    # Hide any remaining empty subplots
    for j in range(i + 1, len(axes)):
        axes[j].axis('off')

    plt.tight_layout()
    plt.suptitle('Histograms of Numerical Features', y=1.02, fontsize=16) # Adjust suptitle position
    plt.show()
else:
    print("No numerical columns found to plot histograms.")

import matplotlib.pyplot as plt
import seaborn as sns

# Identify categorical columns from the data dictionary
categorical_cols_for_plot = data_dictionary_df[
    data_dictionary_df['Inferred/Converted Data Type'] == 'Categorical'
]['Column Name'].tolist()

print(f"Plotting bar plots for {len(categorical_cols_for_plot)} categorical columns...")

# Set up the matplotlib figure and axes for subplots
num_plots = len(categorical_cols_for_plot)
if num_plots > 0:
    # Determine optimal grid size. Max 3 columns per row for readability for categorical plots.
    n_cols = 3
    n_rows = (num_plots + n_cols - 1) // n_cols # Calculate rows needed

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 6, n_rows * 5))
    axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

    for i, col in enumerate(categorical_cols_for_plot):
        if not df[col].empty:
            # Calculate value counts for the categorical column
            value_counts = df[col].value_counts()

            # Limit to top N categories for better visualization if too many unique values
            if len(value_counts) > 10:
                value_counts = value_counts.nlargest(10)

            sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[i], palette='viridis', hue=value_counts.index, legend=False)
            axes[i].set_title(f'Distribution of {col}', fontsize=12)
            axes[i].set_xlabel(col)
            axes[i].set_ylabel('Count')
            axes[i].tick_params(axis='x', rotation=45) # Removed ha='right'
        else:
            # Hide empty subplots if a column couldn't be plotted
            axes[i].axis('off')

    # Hide any remaining empty subplots
    for j in range(i + 1, len(axes)):
        axes[j].axis('off')

    plt.tight_layout()
    plt.suptitle('Bar Plots of Categorical Features', y=1.02, fontsize=16) # Adjust suptitle position
    plt.show()
else:
    print("No categorical columns found to plot bar plots.")